In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("CarPriceDataset_Final.csv")

In [3]:
df.head(10)

,ID,Company,Model,Type,Fuel,Transmission,Engine,Mileage,Kms_driven,Buyers,Horsepower (kw),Year,Price (Lakhs)
0,1,Maruti,Alto,Hatchback,Petrol,Manual,796,19.70,45000,2,32,2010,1.20
1,2,Maruti,Wagon R,Hatchback,Petrol,Manual,998,20.50,40005,2,46,2011,3.00
2,3,Maruti,Wagon R,Hatchback,Petrol,Manual,998,20.50,40005,2,46,2018,4.00
3,4,Maruti,Ertiga,MUV,Petrol,Automatic,1462,18.50,28000,2,73,2012,5.10
4,5,Maruti,Ertiga,MUV,Petrol,Automatic,1462,18.50,40000,2,73,2012,4.00
5,6,Maruti,Swift,Hatchback,Petrol,Automatic,1197,23.50,36000,2,61,2013,1.58
6,7,Maruti,Ignis,Hatchback,Petrol,Automatic,1200,20.89,41000,2,60,2014,2.50
7,8,Maruti,Ignis,Hatchback,Petrol,Automatic,1200,20.89,41000,2,60,2016,3.00
8,9,Maruti,Ciaz,Sedan,Petrol,Automatic,1462,20.04,25000,2,67,2015,6.10
9,10,Maruti,Ciaz,Sedan,Petrol,Automatic,1462,20.04,15000,2,67,2015,5.00

In [5]:
df = df.drop_duplicates()

In [6]:
df.columns.tolist()

['ID',
 'Company',
 'Model',
 'Type',
 'Fuel',
 'Transmission',
 'Engine',
 'Mileage ',
 'Kms_driven',
 'Buyers',
 'Horsepower (kw)',
 'Year',
 'Price (Lakhs)']

In [7]:
df = df.rename(columns={
    'Mileage ': 'Mileage',
    'Horsepower (kw)': 'Horsepower_kw',
    'Kms_driven': 'Km_driven'
})

In [8]:
colonne_fuel = {
    'Gas': 'Petrol',
    'Gasoline': 'Petrol',
    'Eletric': 'Electric',
    'Hybride': 'Hybrid'
}
df['Fuel'] = df['Fuel'].replace(colonne_fuel)

In [10]:
df['Mileage'] = pd.to_numeric(df['Mileage'], errors='coerce')
median_mileage = df['Mileage'].median()
df['Mileage'] = df['Mileage'].fillna(median_mileage)

In [11]:
df.isnull().sum()

ID               0
Company          0
Model            0
Type             0
Fuel             0
Transmission     0
Engine           0
Mileage          0
Km_driven        0
Buyers           0
Horsepower_kw    0
Year             0
Price (Lakhs)    0
dtype: int64

In [12]:
voitures_elec = df['Fuel'] == 'Electric'
if voitures_elec.any():

    elec = df.loc[voitures_elec & (df['Horsepower_kw'] > 0), 'Horsepower_kw']
    if len(elec) > 0:
        moy_elec = elec.mean()
        df.loc[voitures_elec & (df['Horsepower_kw'] == 0), 'Horsepower_kw'] =  moy_elec

C:\Program Files\KMSpico\temp\ipykernel_27740\4055070243.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '195.66666666666666' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[voitures_elec & (df['Horsepower_kw'] == 0), 'Horsepower_kw'] =  moy_elec

In [13]:
df['Price (Lakhs)'] < 1

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Name: Price (Lakhs), Length: 150, dtype: bool

In [14]:
df.describe()

,ID,Engine,Mileage,Km_driven,Buyers,Horsepower_kw,Year,Price (Lakhs)
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,75.500000,2573.346667,15.853333,36673.753333,2.320000,222.046667,2015.553333,62.030733
std,43.445368,1687.191300,6.816246,19426.665542,0.698224,209.008312,3.398651,98.571347
min,1.000000,0.000000,3.800000,3600.000000,2.000000,27.000000,2005.000000,0.800000
25%,38.250000,1462.000000,10.667500,23721.500000,2.000000,74.000000,2014.000000,4.765000
50%,75.500000,1997.000000,15.000000,36000.000000,2.000000,131.000000,2016.000000,19.980000
75%,112.750000,2998.000000,20.040000,45647.250000,2.000000,314.000000,2018.000000,80.000000
max,150.000000,6749.000000,47.450000,130000.000000,5.000000,985.000000,2021.000000,605.000000

In [15]:
df['Price (Lakhs)'].describe()

count    150.000000
mean      62.030733
std       98.571347
min        0.800000
25%        4.765000
50%       19.980000
75%       80.000000
max      605.000000
Name: Price (Lakhs), dtype: float64

In [18]:
df = df.reset_index(drop=True)

In [19]:
prix_outliers = df['Price (Lakhs)'] < 1 
if prix_outliers.any():
    print(f"\n Prix suspects (< 1 lakh) trouvés aux lignes : {df[prix_outliers].index.tolist()}")
    print(df[prix_outliers][['Company', 'Model', 'Year', 'Price (Lakhs)']])

    for idx in df[prix_outliers].index:
        m = df[(df['Company'] == df.loc[idx, 'Company']) & 
                          (df['Model'] == df.loc[idx, 'Model'])]['Price (Lakhs)'].median()
        if not pd.isna(m):
            df.loc[idx, 'Price (Lakhs)'] = m

 Prix suspects (< 1 lakh) trouvés aux lignes : [21, 38]
    Company  Model  Year  Price (Lakhs)
21     Tata   Nano  2006            0.8
38  Hyundai  Verna  2009            0.9

In [21]:
df.to_csv('CarPriceDataset_Ne.csv', index=False)

In [16]:
df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
df['Engine'] = pd.to_numeric(df['Engine'], errors='coerce')
df['Km_driven'] = pd.to_numeric(df['Km_driven'], errors='coerce')
df['Price (Lakhs)'] = pd.to_numeric(df['Price (Lakhs)'], errors='coerce')
df['Horsepower_kw'] = pd.to_numeric(df['Horsepower_kw'], errors='coerce')

In [17]:
df = df.dropna(subset=['Price (Lakhs)', 'Year', 'Engine'])

In [9]:
df.isnull().sum()

ID               0
Company          0
Model            0
Type             0
Fuel             0
Transmission     0
Engine           0
Mileage          3
Km_driven        0
Buyers           0
Horsepower_kw    0
Year             0
Price (Lakhs)    0
dtype: int64